PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/GreetingPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-204
_Add a couple of sentences describing what you did here_
Covert the HTML base page of "Greeting Page" to a vue app. (This card only includes building up the base of the page) 
_Describe what steps you took to test and verify operation of this update_
open the code using the vue app through http://localhost:8080

[MVS-204] Convert "greeting page" to a Vue component

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue

Added a progress bar (v-stepper) along the top and implemented a means to navigate through the set of pages required for a single patient registration.
Built and run the application from my local browswer (Chrome)

Mvs 203 create architecture to display and navigate through single patient registration application process 2

---

PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue

…on) page as a Vue component
https://mass-immunization-system.atlassian.net/browse/MVS-205
Created the "Enter Your Home Address" Page as a Vue component. Included the text fields, drop-down menus and check-boxes needed. 
Tested the code using http://localhost:8080

[MVS-205] Create "Enter your home address" (single patient registration) page as a Vue component

---

PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-207
Created the SinglePatientPersonalInfo component with the elements as specified by the Balsamiq wireframe
I built and ran the application from my local browser (Chrome)

MVS-207 Populate SinglePatientPersonalInfo page

---

PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue

https://mass-immunization-system.atlassian.net/browse/MVS-208
Created fields for first and last name, as well as phone number and phone type (home or cell).
Ran the file in Firefox. Clicked on fields and put in information.

[MVS-208] Created emergency contact page

---

PatientRegistrationApp/src/components/SinglePatientContactInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-206
Implemented Contact Info page for Single Patient Registration to include primary phone number and email address. 
Opened the page with http://localhost:8081/ and ensured the page matches the required components for the wireframe.

Mvs206 create enter your contact info (single patient registration) page as a vue component

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/GreetingPage.vue

…s card
https://mass-immunization-system.atlassian.net/browse/MVS-260
- Updated the "Register myself" and "Register my household" to be a group of toggle buttons 
- Updated the logic to handle the selection of either button
- Updated the logic to know which registration path to go down (single vs. household) based on the button selection
- Updated the App.vue page to avoid showing the progress bar while the Greeting Page is shown (as it is not relevant - we don't know how many steps there will be until the registration path is chosen)
- Updated App.vue to hide the "Next" button unless/until a registration button is selected
Built and ran the app in my local browswer (Chrome)

MVS-260 Make "register myself" and "register my household" selectable in GreetingPage.vue

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
PatientRegistrationApp/src/eventBus.js

https://mass-immunization-system.atlassian.net/browse/MVS-211
Created an event bus to be able to share messages between sibling components
Updated all *.vue files so that the "Review and submit" page for single patient registration displays all entered data (except for the photo - I will create a separate card for that).
Built and run the app locally (Chrome)

[MVS-211] update the review and submit (single patient registration) page to show actual data that has been entered through the ui

---

PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue

…ct.vue page
https://mass-immunization-system.atlassian.net/browse/MVS-255
Linked the required fields of the PersonalInfo Page to the next button. The user will not be able to proceed unless the required fields are filled
Opened the page on the local host and tested it by entering random inputs and leaving some fields empty.

[MVS-255] Implement "required" inputs for SinglePatientEmergencyContact.vue page

---

PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

…ue page
https://mass-immunization-system.atlassian.net/browse/MVS-254
Linked the required fields of the PersonalInfo Page to the next button. The user will not be able to proceed unless the required fields are filled
Opened the page on the local host and tested it by entering random inputs and leaving some fields empty.

[MVS-254] Implement "required" inputs for SinglePatientPersonalInfo.vue page

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-263
Added household contact info to patient registration
Ran patient registration page locally. Clicked household registration then next arrows until contact info page. Ensured that the page matched the required sections necessary for household registration for the contact info page as specified in the card.

Added household contact info

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/HouseholdHomeAddress.vue

https://mass-immunization-system.atlassian.net/browse/MVS-262
Created the address page for the household page, and used the event bus method to use the validate the form.
Used the localhostpage to test it

[MVS-262] Create "Enter your household address" page as a Vue component

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue

… a Vue component
https://mass-immunization-system.atlassian.net/browse/MVS-266
Create the household emergency contact using vue, and use the form validation 
Test using the localhost website

[MVS-266] Create "Specify your emergency contact" (household) page as vue page

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue

…d member #1" page as a Vue component
https://mass-immunization-system.atlassian.net/browse/MVS-264
Create the enter household member #1 page using vue, and using the validation form 
Tested using the localhost website: walk through the form and fill in fields to test the page

[MVS-264] Create "Enter your household personal information: household member #1" page as a Vue component

---

PatientRegistrationApp/src/App.vue

https://mass-immunization-system.atlassian.net/browse/MVS-326
Changed a single line of code in App.vue to enable the container to be centered on the screen. 
Built and ran the application in my local browser (Chrome).  Verified that with any screen resizing (or full-screen), the application remains in the center of the display.

MVS-326 Center application on the screen

---

PatientRegistrationApp/src/App.vue

https://mass-immunization-system.atlassian.net/browse/MVS-328
Changed the v-card and v-toolbar components in App.vue to apply the "flat" style.  Changed the v-stepper component in App.vue to apply the class="elevation-0" style.
Built the application and tested it in my local browser (Chrome).  Verified that the application is displayed without a border or shadow.

[MVS-328] remove border and shadow from overall page component

---

PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/HouseholdRegisterNumber.vue

https://mass-immunization-system.atlassian.net/browse/MVS-261
Updated HouseholdRegisterNumber.vue to provide a dropdown selector for specifying the number of household members.
Updated App.vue to update the progress bar based on the number of household members.
NOTE:  The additional household member pages are not incorporated, yet - this will be part of MVS-268
Built the application and tested it in my local browser (Chrome).  Verified that the single patient workflow still works (including the progress bar) and verified that the progress bar updates according to the number of household members selected.

Mvs 261 create register your household page as a vue component

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue
PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue
PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-388
Adjust all the error messages in the different registration pages:
- Delete all star icons "*"
- Separate the words using a comma 
- Run the vue app using the local host 
- Try and proceed forward without filling some fields to check the error messages 
1. Make sure the words are separated with commas 
2. Make sure there aren't any extra icons in the error message

[MVS-388] Update the error messages in the SinglePatient Pages

---

PatientRegistrationApp/package.json
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/main.js
PatientRegistrationApp/yarn.lock

Finished validation for emergency contact and single patient.
🐬 [JIRA Sprint Card]
https://mass-immunization-system.atlassian.net/browse/MVS-257
📰 [Work Description]
In emergency contact info and single patient info, I made it so the phone number is auto formatted when it is input into the field. The field will only take ()'s -'s and numbers. Red text reminds the user to put in all 10 digits of the phone number.
🚦 [Testing/QA Notes]
I went to single patient contact info page and single patient emergency contact page to put in a phone number.
I tried to put letter and was not allowed to, there was a prompt telling me the phone number had to be 10 digits and once I put the full number the prompt went away.

Made changes for phone validation. [MVS-257]

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue
PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue
PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue

https://mass-immunization-system.atlassian.net/browse/MVS-373
Went through the PatientRegistrationApp and decided to add prepended icons at the beginning of every line of inputs. Doing that would help keep all the lines aligned in the different pages that user will be scrolling through.
- Run the vue app using the localhost 
- Go through the pages of the single patient registration 
- Make sure all the lines are aligned and look presentable 
- Make sure there are icons at the beginning of every line of inputs

[MVS-373] Potential recommendation of using prepended icons in the PatientRegistrationApp

---

node_app/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-435
https://mass-immunization-system.atlassian.net/browse/MVS-436
https://mass-immunization-system.atlassian.net/browse/MVS-437
Setup a node route for:
- GETting a patient resource with resource id
- GETting a patient resource with first and last name, and date of birth
- POSTing a patient resource
Run `docker-compose up --build` in directory with docker-compose.yml file.
Verify FHIR server is running by going to http://localhost:8080/hapi-fhir-jpaserver/.
POSTing patient resource:
- Patient resource examples are available at https://www.hl7.org/fhir/patient-examples.html
- Make a POST request to http://localhost:3000/Patient
- Specify content-type as 'application/json' in headers (XML is not supported at the moment)
- Request body …

[MVS-435] Create Patient endpoint

---

PatientRegistrationApp/src/components/GreetingPage.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue

https://mass-immunization-system.atlassian.net/browse/MVS-375
Added preferred language to review page for both single user and multiple user registration.
Register single and multiple users and ensure preferred language is shown at review page.

[MVS-375] Add preferred language to review page

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-334
Deleted an extra } in the verifyFormContents() function of SinglePatientContactInfo and HouseholdContactInfo
Build and load the application
Verify that there are no build errors

Fix merge issues with contactInfo pages

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-335
Merge fix for MVS-335
Run the patient registration app locally and make sure the email address fields are hidden when "I dont have an email address" is picked

[MVS-335] merge fix for hiding email address fields

---

PointOfDispensingApp/src/components/PatientLookupPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-420
Add the missing text fields in the patient look up page, and replace all placeholders.
- Run the POD software locally
- Go to Retrieve Patient Record page 
- Make sure the last name, first name, date of birth fields are added 
- Make sure all the fields added are working

[MVS-420] Populate/format the Retrieve Patient Record page

---

PointOfDispensingApp/src/components/AdverseEventsComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-427
Format the adverse events page. Added all the missing text fields and select menus
- Run the POD app locally
- Go to Adverse Reaction page 
- Check all the fields added and make sure the formatting is right

[MVS-427] Populate/format AdverseEventsComponent.vue page

---

PointOfDispensingApp/src/components/PatientLookupPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-421
Populate a table in the patient lookup page, and fill it with dummy data like the wireframe shows.
-  Build and load the POD app in a local browser, make sure there are no errors
- Go to Retrieve patient records page 
- Scroll down to check out the table
- Make sure that the outline/ format of the table is correct and corresponds to the wireframe of the page

[MVS-421] Populate/ format table on PatientLookupPage.vue component

---

node_app/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-445
Created an endpoint for patient check-in. Given an appointment id, from QR scanning, or a patient id, from patient lookup, the related appointment and encounter statuses will be updated.
Run `docker-compose up --build` in directory with docker-compose.yml file
1. Create a Patient resource.
2. Create an Appointment resource that:
- has booked status
- references the Patient resource in participant.actor field
3. Create an Encounter resource that:
- has planned status
- references the Patient resource in the subject field
- references the Appointment resource in the appointment field
4. Going to localhost:3000/check-in?patient=_patient_id_ and localhost:3000/check-in?appointment=_appt_id_ should update the status of the …

MVS-445 Create endpoint for check-in

---

PointOfDispensingApp/src/components/VaccinationProceedComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-424
Format the VaccinationProceedComponent.vue page. Replace all the placeholders with the appropriate text fields/ select menus. 
- Run the POD app locally
- Go to "Vaccination Event" page 
- Scroll down and make sure all the required fields are available and functional (refer to the wire frame to make sure all the fields are there)

[MVS-424] populate and Format the VaccinationProceedComponent.vue page

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue

https://mass-immunization-system.atlassian.net/browse/MVS-463
Added "Middle Name" as an optional input field to the SinglePatientPersonalInfo, HouseholdPersonalInfo_1, and HouseholdPersonalInfo_n pages.
Added "middle name" to be rendered in the single patient and household "review and submit pages" as: 
<Last Name>, <First Name> <Middle Name> <Suffix>
- Proceed through the single patient workflow and verify that you are able to enter a middle name for the patient registration
- Verify that the middle name you entered appears on the "review and submit page" (single patient)
- Proceed through the household workflow and enter distinct middle names for each of the patients registered
- Verify that the middle names you entered appear on the "review and submit …

MVS-463-Add-patient-middle-name-as-a-field-for-patient-registration

---

PointOfDispensingApp/src/components/PatientLookupPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-470
Updated PatientLookupPage.vue to adjust the formatting of the Last Name, First Name, and Date of Birth fields.  Also added Zip Code as an optional search parameter.
Build and load the application
Verify that the Last Name, First Name, Date of Birth, and Zip Code fields are formatted with separate labels and input fields (similar to the PatientInfoComponent.vue)

MVS-470 update formatting of patient lookup page.vue

---

PointOfDispensingApp/src/components/PatientHistoryComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-422
Populate a patient history table in the POD app. The table should have 7 columns (Dose Num, Trade Name, Dose Qty., Time Administered, LOT, Practitioner, Adverse Effects)
Dummy Data is used to display the format.
- Run the POD app locally, make sure it compiles without any errors
- Go to patient history tab 
- Make sure that the table has the correct format and headers

[MVS-422] Populate/ format PatientHistoryComponent.vue component

---

PatientRegistrationApp/src/components/GreetingPage.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
PatientRegistrationApp/vue.config.js

Ensured max file size is 2mb's
https://mass-immunization-system.atlassian.net/browse/MVS-339
- Patient(s) Review Page now displays the uploaded photo.
- Images 2mb or larger can not be uploaded as a photo.
- Household review now displays the photos for each patient.
Run the patient registration application. 
Go through single patient and upload a photo on personal info page, try uploading a file larger than 2mb's. 
Upload a valid file, then check to see if the photo displays in review.
Do the same for household patients. (I only tested for a household for two, but I don't think there would be issues if there were more)

[MVS-339] Enabled photo to be seen in review page

---

PatientRegistrationApp/package.json
PatientRegistrationApp/src/components/SinglePatientFollowUp.vue
PatientRegistrationApp/yarn.lock

https://mass-immunization-system.atlassian.net/browse/MVS-498
Generate a QR code depending on the input of a text field. When you write inside the text field, you will get a QR code. Once the QR code is scanned it will give you the text field's input. You will also have the option to …

[MVS-498] connect a QR code generator to a text field

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue

https://mass-immunization-system.atlassian.net/browse/MVS-477
Per MVS-477, the patient registration app has Ethnicity and Race as required single option selection fields. Review and submit page should have formatting fixes, including grammar and removal of []. 
Fill out required …

Mvs 477 make race and ethnicity required fields and more

---

PointOfDispensingApp/src/components/PatientInfoComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-517
Updated the format of PatientInfoComponent to be more dense / space-efficient
- Build and load the PointOfDispensingApp application.
- Navigate to the "Check-In" page
- Verify that the following information is displayed in …

MVS-517 Update PatientInfoComponent.vue

---

PatientRegistrationApp/src/components/GreetingPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-540
Change the Select preferred language text to "Which language would you like to communicate in during your vaccination?" to better represent hat is it meant for. 
- Run the registration app locally 
- Make sure that the …

[MVS-540] Change language selection text in PatRegApp

---

PatientRegistrationApp/package.json
PatientRegistrationApp/src/App.vue
PatientRegistrationApp/src/components/HouseholdFollowUp.vue
PatientRegistrationApp/src/components/SinglePatientFollowUp.vue
PatientRegistrationApp/yarn.lock

https://mass-immunization-system.atlassian.net/browse/MVS-500
Connected the QR code generator to the member's full name. Now when the user proceeds to the follow up page, a QR code is generated. When the QR code is scanned it displays the member's full name in this format: Family Name, …

MVS-500 Generate a QR code based on the member’s registered full name in both single patient and household registration

---

broker/models/Immunization.js
broker/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-446
- Run docker containers
- Create preliminary FHIR resources (referenced FHIR resources must exist)
- Send a POST request to /submit-vaccination with the request data found in models/Immunization and models/Observation
> {
> …

[MVS-446] Create submit vaccination endpoint

---

broker/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-346
Create endpoint to update appointment and encounter status on discharge.
Run `docker-compose up --build` in directory with docker-compose.yml file
1. Create an Appointment resource that:
- has arrived status 
```
POST …
```

[MVS-346] Create discharge endpoint

---

broker/models/EpisodeOfCare.js
broker/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-454
New version of EpisodeOfCare for easy rebasing. model is still in models folder under broker.
postman request:
http://localhost:3000/EpisodeOfCare
body:
{ "EpisodeOfCare": { "status" : "planned", "patient" : …

Mvs 454 endpoint for episode of care

---

broker/models/Practitioner.js
broker/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-456
Updated the Practitioner endpoint to be modularized. Body of the practitioner code is now under models in the broker folder.
postman request:
http://localhost:3000/Practitioner
body:
`{
"Practitioner":
{
"family" : "George", …

Mvs 456 create node endpoint for practitioner

---

broker/models/Location.js
broker/server.js

https://mass-immunization-system.atlassian.net/browse/MVS-455
Updated the Practitioner endpoint to be modularized. Body of the Location code is now under models in the broker folder.
postman request:
http://localhost:3000/Location
body:
`{
"Location":
{
"status" : "active",
"name": …

Mvs 455 create node endpoint for location resource

---

PointOfDispensingApp/src/brokerRequests.js
PointOfDispensingApp/src/components/PatientCheckInComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-550
Call /healthcheck endpoint from POD Check-in component
1. Follow build instructions in README
2. Go to http://localhost:3000/pod/#/CheckIn
3. 'Patient Information Verified' should result in a "Success!" message in the …

[MVS-550] Connect to API from Check-in

---

PointOfDispensingApp/src/brokerRequests.js
PointOfDispensingApp/src/components/PatientCheckInComponent.vue
PointOfDispensingApp/src/components/PatientDischargeComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-553
Call /healthcheck endpoint from POD Discharge component
1. Follow build instructions in README
2. Go to http://localhost:3000/pod/#/Discharge
3. 'End Encounter' should result in a "Success!" message in the browser console, …

[MVS-553] Connect Discharge to API

---

PointOfDispensingApp/src/brokerRequests.js
PointOfDispensingApp/src/components/PatientCheckInComponent.vue
PointOfDispensingApp/src/components/VaccinationCanceledComponent.vue
PointOfDispensingApp/src/components/VaccinationProceedComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-551
Call /healthcheck endpoint from POD VaccinationEvent component
1. Follow build instructions in README
2. Go to http://localhost:3000/pod/#/VaccinationEvent
3. Answer the questions and select 'Yes' when prompted to proceed …

[MVS-551] Connect Vaccination Event to API

---

PatientRegistrationApp/src/components/HouseholdFollowUp.vue

https://mass-immunization-system.atlassian.net/browse/MVS-561
When the "Download As PDF" button is clicked, a pdf is generated of all the QR codes of the household members registered. Every two QR codes are presented on a single pdf page. Each page of the pdf includes 2 sentences …

[MVS-561] Connect the download button to a pdf file generator in the household follow up page

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue

https://mass-immunization-system.atlassian.net/browse/MVS-559
The WIR’s “Relationship” options are a bit different:  Spouse, Parent, Guardian, Care Giver, Sibling, Grandparent, Child, Foster Child, Stepchild, Other
This card was used to update the registration type options in the …

[MVS-559] Update the relationship options to match the WIR options

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

Changed formatting of date of birth string within the Patient Registration Component.
https://mass-immunization-system.atlassian.net/browse/MVS-478
Changed formatting of date from 'Year-Month-Day' to 'Month/Day/Year', following a more normal date convention.
Run the patient registration application. Try to put in invalid dates and confirm the app throws errors when needed. Put in a valid date manually and through the date picker, proceed through registration workflow.
Check the console to see if errors are thrown in the process.

[MVS-478] Implemented date formatting within Patient Registration Component

---

broker/config/server.js
broker/endpoints/Appointment.js
broker/endpoints/CheckIn.js
broker/endpoints/Discharge.js
broker/endpoints/Encounter.js
broker/endpoints/EpisodeOfCare.js
broker/endpoints/Immunization.js
broker/endpoints/Location.js
broker/endpoints/Observation.js
broker/endpoints/Organization.js
broker/endpoints/Patient.js
broker/endpoints/Practitioner.js
broker/models/Appointment.js
broker/models/Encounter.js
broker/models/EpisodeOfCare.js
broker/models/Immunization.js
broker/models/Location.js
broker/models/Observation.js
broker/models/Organization.js
broker/models/Patient.js
broker/models/Practitioner.js
broker/server.js
broker/services/axiosInstance.js
broker/testing/EndpointsUnitTest.js
broker/testing/examples.js

- Refactor: Separate endpoint handling and logic in broker/server.js
- Add a program to facilitate testing
- Run broker/testing/EndpointsUnitTest.js (instructions in file)
- Ensure output of the program matches the inputs in broker/testing/examples.js
- Test check-in and discharge …

Refactor broker

---

PointOfDispensingApp/src/brokerRequests.js
broker/testing/EndpointsUnitTest.js
broker/testing/examples.js

Fixed an issue with patient search
1. Build and run, details in readme
2. Run broker/testing/EndpointsUnitTest.js, details in file. This will create an example patient resource
3. Go to http://localhost:3000/pod/#/RetrievePatientRecord and search for the example patient. Last name: …

Patient search fix

---

PointOfDispensingApp/src/App.vue
PointOfDispensingApp/src/components/PatientHistoryComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-573
Added date calculation function to display the number of days between the current date and the initial vaccination of the patient in the Patient History page. 
Build and load the POD application with the backend also up and …

Mvs 573 add days since last vax

---

PatientRegistrationApp/package.json

_Add a couple of sentences describing what you did here_
Added axios as a dependency for PatientRegistration so that the Vue app compiles
_Describe what steps you took to test and verify operation of this update_
Navigate to …

Axios added as dependency for PatientRegistration

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-541
Removed datepicker from patient registration app.
Build and run patient registration, confirm:
- date can be input with no issues for single patient/household members.
- Invalid dates (ex: 40/20/2020) do not work

[MVS-541] Remove date picker component

---

broker/server.js

Front-end apps are sending requests with broker/ prepended, which is needed for the second method for building the project, but fails for the third method.

Fix compatibility issue

---

PointOfDispensingApp/src/components/PatientLookupPage.vue

https://mass-immunization-system.atlassian.net/browse/MVS-645
Reworked the layout of the last name, first name, date of birth, and zip code fields so that the tab order is: last name > first name > date of birth > zip code.
Updated the zip code field label to be "Zip code (optional" …

MVS-645 Updates/corrections to "Retrieve Patient Record" page in POD app

---

PatientRegistrationApp/src/components/GreetingPage.vue
PatientRegistrationApp/src/customerSettings.js

https://mass-immunization-system.atlassian.net/browse/MVS-650
Add an into text on the first page of the PatReg app explaining to the patient what to expect out of this registration. Add the text to customerSettings.js file so it can be easily accessed and changed according to the …

[MVS-650] Add a PatReg intro text on the greeting page

---

PatientRegistrationApp/src/components/HouseholdContactInfo.vue
PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue
PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
PatientRegistrationApp/src/components/ScreeningQuestions.vue
PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue

https://mass-immunization-system.atlassian.net/browse/MVS-537
Fix the text fields validation logic. Make sure that when the user puts in an invalid input, it would proceed to the next page until it's fixed. This logic was updated on the phone number, email, zipcode, and DOB text fields …

[MVS-537] Update zip code, phone, email, DOB validation logic and fix a spelling error

---

PatientRegistrationApp/src/App.vue

https://mass-immunization-system.atlassian.net/browse/MVS-657
Add an exit text, explaining to the user what does the submission of the work flow means, to the pop up message in the review and submit page of the workflow.
- Run the PatReg app 
- Go through both the single patient and …

[MVS-657] Add exit text to the pop up in the Review and Submit page

---

PointOfDispensingApp/src/brokerRequests.js
PointOfDispensingApp/src/components/PatientCheckInComponent.vue
broker/endpoints/Appointment.js
broker/endpoints/CheckIn.js
broker/endpoints/Encounter.js
broker/models/Encounter.js
broker/server.js
broker/testing/checkInDischargeTest.js
broker/testing/examples.js

https://mass-immunization-system.atlassian.net/browse/MVS-659
Update check-in endpoint to create a new Encounter resource on check-in
Run broker/testing/EndpointsUnitTest.js to setup data or create Patient through registration application.
Check-in patient, Joe Bush 11/11/1999, or with …

[MVS-659] Create Encounter on Check-in

---

broker/endpoints/Patient.js

Base url is defined in axiosInstance. Adding the base to the endpoint results in issues when broker is run on docker.
1. In .env, specify the variable `FHIR_URL_BASE=http://hapi:8080/hapi-fhir-jpaserver/fhir`
2. Build with `docker-compose up --build`
3. Test patient lookup

Remove redundant base url

---

.github/workflows/format_prettier.yml

https://mass-immunization-system.atlassian.net/browse/MVS-661
Add a github workflow that will automatically format code using prettier https://prettier.io/
Tested on a fork

Add automatic code formatter

---

PatientRegistrationApp/src/components/ScreeningQuestions.vue
PointOfDispensingApp/src/components/VaccinationScreeningComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-702

Fix spelling in screening pages

---

PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
broker/endpoints/Patient.js
broker/models/Patient.js
broker/models/RelatedPerson.js
broker/testing/examples.js

https://mass-immunization-system.atlassian.net/browse/MVS-693
Store race and ethnicity in FHIR resource using US Core Extension
Register patient with registration app
Access patient resource through HAPI server
- Go to localhost:3000/Patient/_QR\_VALUE_ to view resource id
- Go to …

Store patient race and ethnicity in FHIR

---

PointOfDispensingApp/src/components/PatientLookupPage.vue

_Describe what steps you took to test and verify operation of this update_

Fix birthdate field of Patient Lookup

---

PointOfDispensingApp/src/components/VaccinationProceedComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-725
The barcodes on the vaccine vial don’t actually contain all of the information we anticipated it would contain (lot number, expiration date).  Plus, the doses are distributed to syringes, so the barcodes are not accessible …

[MVS-725] Remove the scan vaccine barcode button

---

PointOfDispensingApp/src/store/store.js

https://mass-immunization-system.atlassian.net/browse/MVS-708
This was a very simple change - I just removed the status=booked restriction when looking up an Appointment. Everything else looks to work as expected.
I checked in for a 2nd and then a 3rd visit.

MVS-708: Implement 2nd dose functionality in POD app

---

PointOfDispensingApp/src/components/VaccinationCanceledComponent.vue
PointOfDispensingApp/src/components/VaccinationProceedComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-511
Prevent user from proceeding (in vaccination event page) if required fields are not filled
Try submitting a vaccination event without filling all required fields.

[MVS-511] Validate vaccination event components

---

PointOfDispensingApp/src/brokerRequests.js
PointOfDispensingApp/src/components/PatientHistoryComponent.vue

https://mass-immunization-system.atlassian.net/browse/MVS-655
Display days since vaccination in history table.
Days since vaccination is displayed on check-in page.

[MVS-655] Display days since last vaccination

---

PointOfDispensingApp/src/components/PatientLookupPage.vue
PointOfDispensingApp/src/components/VaccinationProceedComponent.vue
PointOfDispensingApp/src/utils/commonFormValidation.js
broker/models/ImmunizationCompleted.js
broker/testing/examples.js

https://mass-immunization-system.atlassian.net/browse/MVS-724
Format vaccine expiration date
Expiration dates before the current date, or are more than a year after the current date return an error.
Submit vaccination event works.

[MVS-724] Format vaccine expiration date
