david-fraley/MassVaccinationSystem

- PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
https://mass-immunization-system.atlassian.net/browse/MVS-258
Made email able to be validated as a proper email. 
Example email is shown to the user to give them a guide on how to write the email.
Email field will also validate if left blank, allowing users to complete the form if they do not have an email.
The general code was reformatted for clarity.
Ran the project and tested on Firefox.
> Made email able to be validated as a proper email

- PatientRegistrationApp/src/App.vue
https://mass-immunization-system.atlassian.net/browse/MVS-327
Swapped the order of v-toolbar and v-stepper-header in App.vue
Built and ran the application in my local browser (Chrome).  Verified that the page title bar and progress bar have been swapped.
> [MVS-327] swap header bar with progress bar

- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
https://mass-immunization-system.atlassian.net/browse/MVS-256
Updated Single Patient Home Address page so that user can only enter a valid zip code either in the format ##### or #####-####
Ran the application on the local drive
Single patient registration then navigate to Home Address page and enter information
Zip code field shows if entry is incorrect with numbers, symbols, or letters
Zip code field should only allow entry that has format ##### or #####-####
> Mvs 256 validate zip code field in single patient home address.vue page

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
#54  :flipper: [JIRA Sprint Card]
https://mass-immunization-system.atlassian.net/browse/MVS-370
Extended the length of the home address field in single/ household registration
- run the vue app through the local host 
- go to the home address page in the single and household registration 
- make sure that the "home address" text field takes up the whole line
> [MVS-370] Extend the length of the "Home Address" field for the single and household registration

- PatientRegistrationApp/src/components/GreetingPage.vue
https://mass-immunization-system.atlassian.net/browse/MVS-331
Anchor and adjust line spacing so information doesn't pop up across the entire screen in the greeting page
- run the vue app using the local host 
- hover over the household registration and make sure that the tooltip pops up on the right bottom corner of the button 
- make sure that the tooltip doesn't cover the whole screen and that it has a specific width
> [MVS-331] Anchor and adjust line spacing so information doesn't pop up across entire screen

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
https://mass-immunization-system.atlassian.net/browse/MVS-387
Make USA a default for the country select menu in the HomeAddress page for both Household and single patient registration
- Run the vue app using the localhost 
- Go through the work flow of a single patient and household registration 
- Make sure that the country select menu is set to default (USA) before filling it
> [MVS-387] Autofill country to be USA in Home Address fields

- PatientRegistrationApp/src/components/HouseholdContactInfo.vue
- PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue
https://mass-immunization-system.atlassian.net/browse/MVS-432
In household emergency contact info and household patient info, the phone number only accepts numbers, dashes '-', and brackets '()' and autoformats the field. Red text reminds the user to put in all 10 digits of the phone number.
_Describe what steps you took to test and verify operation of this update_
Register a household with the required fields. In the household patient info and emergency contact pages, enter a phone number. Ensure that numbers, dashes '-', and brackets '()' are the only valid entries in these fields. The field was tested for numbers, symbols, and letters to ensure the formatting stayed consistent throughout entries.
> Mvs 432 validate phone number fields in household vue pages

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
…ked in single patient registration
https://mass-immunization-system.atlassian.net/browse/MVS-333
Add radio buttons to the home address page. Then make sure that when the user picks I dont have an address, the address fields are hidden, and the user can proceed 
- Run the patient registration app locally 
- Go to the Home Address page 
- Make sure that when "I dont have a home address" radio button is picked, the text fields are hidden
> [MVS-333] Hide home address fields when I dont have an address is picked

- PatientRegistrationApp/src/components/HouseholdContactInfo.vue
- PatientRegistrationApp/src/components/SinglePatientContactInfo.vue
Disable the email address fields when the user picks "I have no email address" 
- Run the vue.app using a local host 
- check the single patient registration contact info page, and switch between "i have an email address" and "I have no email address" 
- Do the same for the household registration Contact Info page
> [MVS-335] Decrease transparency on Email Address options until verified they have one

- PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
- PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
https://mass-immunization-system.atlassian.net/browse/MVS-389
- Prevent users from choosing a DOB in the future
- Add text input for DOB field
The max date for DOB is set by the current date time. However, there were issues because the date time used was in UTC timezone. Therefore, depending on the local timezone, the max date could be a day in advance. For example, EST is UTC -5 (EST is five hours behind UTC). At 7pm EST, it would be 12am UTC, the next date.
- To test the fix, open the date picker at a time when UTC date time is a day ahead local date time. Ensure the date picker does not allow dates in the future, relative to local region.
- The DOB should be able to be entered through the text field, and only valid dates are accepted.
- Verify the proper DOB information is displayed on …
> MVS 389 Restrict DOB Dates

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
- PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-464
Changed "Home Address" (single field) into "Address Line 1" and "Address Line 2."  Updated SinglePatientHomeAddress, HouseholdHomeAddress, SinglePatientReviewSubmit, and HouseholdReviewSubmit accordingly.
Complete the following for the single AND household workflows:
- Enter a single-line home address
- Proceed to the "review and submit" page and verify that the address is represented correctly
- Go back and enter a 2-line address (e.g. specify "Apartment 2B" as address line 2)
- Proceed to the "review and submit" page and verify that the address is represented correctly; address line 1 should be on the first line, followed by address line 2
> Added Line Address 2

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
- PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-465
Note!  This branch is off of MVS-464
Removed "County" from SinglePatientHomeAddress, HouseholdHomeAddress, SinglePatientReviewSubmit, and HouseholdReviewSubmit
Adjusted the sizes of the remaining address fields accordingly.
- Proceed to the page for entering the single patient home address.  Verify that "County" is no longer an option.
- Proceed to the single patient "review and submit" page.  Verify that the county is no longer displayed.
- Proceed to the page for entering the household home address.  Verify that "County" is no longer an option.
- Proceed to the household "review and submit" page.  Verify that the county is no longer displayed.
> Mvs 465 remove county as a field for patient registration

- PointOfDispensingApp/src/components/VaccinationScreeningComponent.vue
https://mass-immunization-system.atlassian.net/browse/MVS-423
Updated VaccinationScreeningComponent.vue to match the formatting of the associated wireframe.
Made the "Proceed with vaccination?" box only visible once the screening checklist has been completed.
- Build and load the application; verify that there are no build errors
- Navigate to the "Vaccination Event" left menu option
- Verify that the screening checklist (4 items) is presented with an associated set of Yes/No radio buttons
- Verify that unless/until the screening checklist is completed (with either Yes or No responses), the "Proceed with vaccination?" box (and associated radio buttons) are not visible.
> Mvs 423 format vaccination screening component.vue component

- PointOfDispensingApp/src/components/PatientInfoComponent.vue
… to also have the "outlined" attribute
https://mass-immunization-system.atlassian.net/browse/MVS-468
update the readonly text fields to have an outlined attribute in the Patient Info Component (patient ID, Last name, First name, DOB, Gender,...)
- Run the POD app locally, make sure it compiles without errors
- Go to Check In page 
- Make sure that the Patient Info text fields are outlined and read-only
> [MVS-468] Update the readonly text fields of PatientInfoComponent.vue to also have the "outlined" attribute

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
…dress page
https://mass-immunization-system.atlassian.net/browse/MVS-473
Use the same zipcode validation method in the single patient home address page, in the household home address page.
- Run the patient registration app locally, make sure it compiles without any errors
- Go to the household home address page 
- Experiment with the zip code field and make sure it works properly (try inputting letters, more than 5 numbers, ...)
> [MVS-473] Need to implement zip code validation for Household home address page

- PatientRegistrationApp/src/App.vue
- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
- PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-466
Made the following changes to the single patient home address page and the household home address page:
- Removed the “I have/do not have a home address” radio buttons and associated show/hide logic.
- Added an “Address Type” dropdown field with the options of “Home,” "Business," and “Temporary.”  
- Made “Address Type” required and included it in the page validation (verifyFormContents function).
Made the following changes to the single patient review and submit page and household review and submit page:
- Added the display of “Address Type”
- Removed the headings for street address, city, zip code, country (those are obvious)
- Complete the single patient registration process, specifically …
> MVS-466 add patient address type as a field for patient registration

- PointOfDispensingApp/config.js
- PointOfDispensingApp/src/components/VaccinationEventPage.vue
- PointOfDispensingApp/src/components/VaccinationScreeningComponent.vue
https://mass-immunization-system.atlassian.net/browse/MVS-469
NOTE:  This branch is based on MVS-423
Implemented changes to make the "Proceed with vaccination?" response determine whether the VaccinationProceedComponent.vue or the VaccinationCanceledComponent.vue is displayed.  Until that "Proceed with vaccination?" question is answered, neither VaccinationProceedComponent.vue nor the VaccinationCanceledComponent.vue are displayed.
- Go to the Vaccination Event page
- Verify that there is nothing displayed below the vaccination screening questions
- Complete the 4 screening questions along the left side
- The "Proceed with vaccination?" question will be displayed once the 4 screening questions are answered
- Select "yes" - verify that the …
> Mvs 469 implement logic in vaccination event page.vue to show/hide vaccination proceed component.vue or vaccination canceled component.vue

- PointOfDispensingApp/src/components/VaccinationCanceledComponent.vue
https://mass-immunization-system.atlassian.net/browse/MVS-425
Added the appropriate elements to the  Vaccination Canceled component. 
The new component is found under vaccination event tab, after you check the 4 Yes/No questions and click No for 'proceed with vaccination'.
This component should throw no errors when being interacted with. 
This component should closely match the mockup shown here 
https://mass-immunization-system.atlassian.net/jira/software/projects/MVS/boards/2?selectedIssue=MVS-425
> [MVS-425] Finished populating VaccinationCanceletedComponent

- PatientRegistrationApp/src/components/HouseholdPersonalInfo_1.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
- PatientRegistrationApp/src/components/SinglePatientPersonalInfo.vue
https://mass-immunization-system.atlassian.net/browse/MVS-527
Change the Suffix field from a text field to a select menu. Add these options to the select menu: II, III, IV, Jr, Sr. 
Make sure you do so for the single patient personal info page, Household personal info1 page and …
> [MVS-527] Provide dropdown list of suffix options on Personal Info page in PatRegApp

- PatientRegistrationApp/src/components/HouseholdHomeAddress.vue
- PatientRegistrationApp/src/components/SinglePatientHomeAddress.vue
https://mass-immunization-system.atlassian.net/browse/MVS-556
Remove "Business" as an option for Address Type drop down menu. Per discussion with Waukesha County, we need to remove the “Business” option, as it may complicate the patient match-up in the WIR system.
- Run the Patient …
> [MVS-556] Remove business option from address type drop down menu

- PointOfDispensingApp/src/components/PatientDischargeComponent.vue
- PointOfDispensingApp/src/components/VaccinationCanceledComponent.vue
- PointOfDispensingApp/src/components/VaccinationProceedComponent.vue
https://mass-immunization-system.atlassian.net/browse/MVS-607
Updated VaccinationProceedComponent and VaccinationCanceledComponent to call submitVaccinationRecord as well as endEncounter upon clicking on the "Submit Vaccination Record" button.  The page auto-advances to the discharge …
> MVS-607 Combine patient discharge with the submission of the vaccination record

- PointOfDispensingApp/src/components/VaccinationProceedComponent.vue
https://mass-immunization-system.atlassian.net/browse/MVS-557
Updated VaccinationProceedComponent to remove the unnecessary/redundant vaccination status and time stamp fields. 
Retrieve a patient record and check the patient in.
On the Vaccination Event page, complete the screening …
> MVS-557 "Vaccination Status" and associated "Date/Time" are not necessary in VaccinationProceedComponent.vue

- PatientRegistrationApp/src/components/HouseholdEmergencyContact.vue
- PatientRegistrationApp/src/components/HouseholdPersonalInfo_n.vue
- PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
- PatientRegistrationApp/src/components/SinglePatientEmergencyContact.vue
- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-535
Updated the single patient and household registration "emergency contact" pages to capture the relationship (as an optional field).  Updated the "review and submit" pages to also show the relationship.
- Build and load the …
> Mvs-535 update pat reg to include emergency contact relationship type

- PointOfDispensingApp/src/App.vue
https://mass-immunization-system.atlassian.net/browse/MVS-687
Updated App.vue in the PointOfDispensingApp to comment out the code that displays the "Configuration" menu item.
Build and load the POD application using any of the means described in README.md.
Verify that there is no …
> MVS-687 Hide "Configuration" menu item in the POD app

- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-696
The incorrect property name was being referenced, so the patient contact info was not being sent to the broker
Repeat for single and household workflows 
- Register at least one user through the registration app
- After …
> Fix: Send patient contact info

- PointOfDispensingApp/src/store/store.js
https://mass-immunization-system.atlassian.net/browse/MVS-729
We can save the user a couple of clicks if we just auto-select the 0.5 mL option for the “Dose Quantity” field. This card sets the 0.5 mL quantity as a default in the POD app
- Run the POD app
- Go through the check in …
> [MVS-729] Set default dose quantity to 0.5 mL in POD app

- PatientRegistrationApp/src/App.vue
- PatientRegistrationApp/src/components/HouseholdReviewSubmit.vue
- PatientRegistrationApp/src/components/SinglePatientReviewSubmit.vue
https://mass-immunization-system.atlassian.net/browse/MVS-728
This PR adds "in progress" indicator upon attempting to submit patient registration info
Cases where there should be a spinner:
At the Patient Registration- final review page "Are you sure?" pop-up>click "Yes" point, there …
> Mvs 728 add in progress indicator while submitting patient record to backend
